---
# vim:sw=2:ft=ansible

- name: wsgi restart
  service: name={{item.name}}-wsgi state=restarted
  with_items: "{{wsgi_applications}}"
  become: yes

- name: wsgi reload
  service: name={{item.name}}-wsgi state=reloaded
  with_items: "{{wsgi_applications}}"
  become: yes

- name: nginx restart
  service: name=nginx state=restarted
  become: yes

- name: nginx reload
  service: name=nginx state=reloaded
  become: yes
